name: Auto Assign
on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
          addReviewers: true
          addAssignees: true
          numberOfReviewers: 1
          numberOfAssignees: 1
          reviewers: |
            /team-plowin
          assignees: |
            this-is-an-unknown-assignee
            /team-plowin
          skipKeywords: wip
          excludeLabels: dependencies, wip
